<?xml version="1.0"?>
<robot name="tracked_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Robot dimensions from specifications -->
  <xacro:property name="robot_length" value="1.070"/> <!-- 1070mm in meters -->
  <xacro:property name="robot_width" value="0.820"/> <!-- 820mm in meters -->
  <xacro:property name="robot_height" value="0.680"/> <!-- 680mm in meters -->
  <xacro:property name="track_wheel_diameter" value="0.190"/> <!-- 190mm in meters -->
  <xacro:property name="track_width" value="0.176"/> <!-- 176mm in meters -->
  
  <!-- Calculated properties -->
  <xacro:property name="chassis_length" value="${robot_length * 0.9}"/> <!-- Slightly smaller than full length -->
  <xacro:property name="chassis_width" value="${robot_width - 2*track_width}"/> <!-- Width minus tracks -->
  <xacro:property name="chassis_height" value="${robot_height * 0.8}"/> <!-- Main body height -->
  <xacro:property name="track_length" value="${robot_length}"/> <!-- Track length -->
  <xacro:property name="wheel_radius" value="${track_wheel_diameter/2}"/> <!-- Wheel radius -->
  <xacro:property name="wheel_thickness" value="${track_width * 0.9}"/> <!-- Slightly thinner than track -->
  <xacro:property name="camera_width" value="0.1"/>
  <xacro:property name="camera_height" value="0.12"/>
  <xacro:property name="camera_depth" value="0.08"/>

  <!-- Materials for visualization -->
  <material name="yellow">
    <color rgba="1.0 0.8 0.0 1.0"/>
  </material>
  
  <material name="black">
    <color rgba="0.1 0.1 0.1 1.0"/>
  </material>
  
  <material name="gray">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>
  
  <material name="dark_gray">
    <color rgba="0.3 0.3 0.3 1.0"/>
  </material>
  
  <material name="camera_material">
    <color rgba="0.2 0.2 0.2 1.0"/>
  </material>
  
  <material name="camera_lens">
    <color rgba="0.1 0.3 0.4 0.7"/>
  </material>

  <!-- Base link - robot center at ground level -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${chassis_height/2 + wheel_radius*0.4}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="yellow"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${chassis_height/2 + wheel_radius*0.4}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${chassis_height/2 + wheel_radius*0.4}" rpy="0 0 0"/>
      <mass value="50.0"/>
      <inertia 
        ixx="5.0" ixy="0.0" ixz="0.0" 
        iyy="5.0" iyz="0.0" izz="5.0"/>
    </inertial>
  </link>

  <!-- Camera mount -->
  <link name="camera_mount">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_width*1.2} ${camera_width*1.2} ${camera_height*0.5}"/>
      </geometry>
      <material name="dark_gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_width*1.2} ${camera_width*1.2} ${camera_height*0.5}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia 
        ixx="0.01" ixy="0" ixz="0" 
        iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <joint name="camera_mount_joint" type="fixed">
    <origin xyz="${chassis_length*0.2} 0 ${chassis_height + wheel_radius*0.4}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="camera_mount"/>
  </joint>

  <!-- Camera -->
  <link name="camera">
    <visual>
      <origin xyz="0 0 ${camera_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_depth} ${camera_width} ${camera_height}"/>
      </geometry>
      <material name="camera_material"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${camera_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_depth} ${camera_width} ${camera_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <inertia 
        ixx="0.005" ixy="0" ixz="0" 
        iyy="0.005" iyz="0" izz="0.005"/>
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <origin xyz="0 0 ${camera_height*0.25}" rpy="0 0 0"/>
    <parent link="camera_mount"/>
    <child link="camera"/>
  </joint>

  <!-- Camera lens -->
  <link name="camera_lens">
    <visual>
      <origin xyz="${camera_depth*0.3} 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <cylinder radius="${camera_width*0.25}" length="${camera_depth*0.4}"/>
      </geometry>
      <material name="camera_lens"/>
    </visual>
    <collision>
      <origin xyz="${camera_depth*0.3} 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <cylinder radius="${camera_width*0.25}" length="${camera_depth*0.4}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia 
        ixx="0.001" ixy="0" ixz="0" 
        iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="camera_lens_joint" type="fixed">
    <origin xyz="${camera_depth/2} 0 ${camera_height*0.7}" rpy="0 0 0"/>
    <parent link="camera"/>
    <child link="camera_lens"/>
  </joint>

  <!-- Left track assembly -->
  <link name="left_track_base">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${track_length} ${track_width} ${wheel_radius*0.5}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${track_length} ${track_width} ${wheel_radius*0.5}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="10.0"/>
      <inertia 
        ixx="0.5" ixy="0.0" ixz="0.0" 
        iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

  <joint name="left_track_joint" type="fixed">
    <origin xyz="0 ${(chassis_width+track_width)/2} ${wheel_radius*0.25}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="left_track_base"/>
  </joint>

  <!-- Right track assembly -->
  <link name="right_track_base">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${track_length} ${track_width} ${wheel_radius*0.5}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${track_length} ${track_width} ${wheel_radius*0.5}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="10.0"/>
      <inertia 
        ixx="0.5" ixy="0.0" ixz="0.0" 
        iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

  <joint name="right_track_joint" type="fixed">
    <origin xyz="0 -${(chassis_width+track_width)/2} ${wheel_radius*0.25}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="right_track_base"/>
  </joint>

  <!-- Wheels for tracks - These will be made to rotate to show track movement -->
  <!-- Left front wheel - Drive wheel -->
  <link name="left_front_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <inertia 
        ixx="0.1" ixy="0.0" ixz="0.0" 
        iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
  </link>

  <joint name="left_front_wheel_joint" type="continuous">
    <origin xyz="${robot_length/2 - wheel_radius} 0 0" rpy="0 0 0"/>
    <parent link="left_track_base"/>
    <child link="left_front_wheel"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <!-- Left rear wheel -->
  <link name="left_rear_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <inertia 
        ixx="0.1" ixy="0.0" ixz="0.0" 
        iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
  </link>

  <joint name="left_rear_wheel_joint" type="continuous">
    <origin xyz="-${robot_length/2 - wheel_radius} 0 0" rpy="0 0 0"/>
    <parent link="left_track_base"/>
    <child link="left_rear_wheel"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <!-- Right front wheel - Drive wheel -->
  <link name="right_front_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <inertia 
        ixx="0.1" ixy="0.0" ixz="0.0" 
        iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
  </link>

  <joint name="right_front_wheel_joint" type="continuous">
    <origin xyz="${robot_length/2 - wheel_radius} 0 0" rpy="0 0 0"/>
    <parent link="right_track_base"/>
    <child link="right_front_wheel"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <!-- Right rear wheel -->
  <link name="right_rear_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <inertia 
        ixx="0.1" ixy="0.0" ixz="0.0" 
        iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
  </link>

  <joint name="right_rear_wheel_joint" type="continuous">
    <origin xyz="-${robot_length/2 - wheel_radius} 0 0" rpy="0 0 0"/>
    <parent link="right_track_base"/>
    <child link="right_rear_wheel"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <!-- Track visual elements (simplified representation of the actual tracks) -->
  <!-- Left track visual -->
  <link name="left_track_visual">
    <visual>
      <origin xyz="0 ${track_width/4} 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://robot_navigation/urdf/meshes/simple_track.dae" scale="${track_length/2} ${track_width} ${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <joint name="left_track_visual_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="left_track_base"/>
    <child link="left_track_visual"/>
  </joint>

  <!-- Right track visual -->
  <link name="right_track_visual">
    <visual>
      <origin xyz="0 -${track_width/4} 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://robot_navigation/urdf/meshes/simple_track.dae" scale="${track_length/2} ${track_width} ${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <joint name="right_track_visual_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="right_track_base"/>
    <child link="right_track_visual"/>
  </joint>

  <!-- Transmission elements for the wheels -->
  <transmission name="left_front_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_front_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_front_wheel_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="right_front_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_front_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_front_wheel_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="left_rear_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_rear_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_rear_wheel_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="right_rear_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_rear_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_rear_wheel_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <!-- Gazebo plugins for control -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/tracked_robot</robotNamespace>
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
    </plugin>
  </gazebo>

  <!-- Add a camera sensor to the model -->
  <gazebo reference="camera">
    <sensor type="camera" name="camera_sensor">
      <update_rate>30.0</update_rate>
      <camera name="camera">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>0.0</updateRate>
        <cameraName>tracked_robot/camera</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>camera</frameName>
        <hackBaseline>0.07</hackBaseline>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Define different colors for Gazebo -->
  <gazebo reference="base_link">
    <material>Gazebo/Yellow</material>
  </gazebo>

  <gazebo reference="left_track_base">
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="right_track_base">
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="left_front_wheel">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="right_front_wheel">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="left_rear_wheel">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="right_rear_wheel">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="camera_mount">
    <material>Gazebo/DarkGrey</material>
  </gazebo>

  <gazebo reference="camera">
    <material>Gazebo/Black</material>
  </gazebo>

</robot>
